#!/bin/sh

set -e

# Promote
PG_BKP_CMD=""
if [ $(id -u) -eq 0 ] ; then
  su-exec postgres pg_ctl promote --wait
  PG_BPK_CMD="su-exec postgres pg_basebackup"
else
  pg_ctl promote --wait
  PG_BPK_CMD="pg_basebackup"
fi

# Take an immediate backup
rm -rf /archives/base/bak
mv /archives/base/cur /archives/base/bak
mkdir /archives/base/cur
[ $(id -u) -eq 0 ] && chown postgres:postgres /archives/base/cur
$PG_BPK_CMD \
  --format tar \
  --pgdata /archives/base/cur \
  --gzip

touch /archives/base/cur/backup.done

# Cleanup any WAL archives no longer used
pg_archivecleanup /archives/wal $(basename $(ls -t /archives/wal/*.backup | head -n1))
