#!/bin/sh

set -e

# Promote
pg_ctl promote --wait

# Take an immediate backup
rm -rf /archives/base/bak
mv /archives/base/cur /archives/base/bak
mkdir /archives/base/cur
pg_basebackup --format tar --pgdata /archives/base/cur --gzip

# Verify backup
tar tf /archives/base/cur/base.tar.gz   >/dev/null
tar tf /archives/base/cur/pg_wal.tar.gz >/dev/null
touch /archives/base/cur/backup.done

# Cleanup any WAL archives no longer used
pg_archivecleanup /archives/wal $(basename $(ls -t /archives/wal/*.backup | head -n1))
