#!/bin/sh

set -e

mkdir -p /var/lib/postgresql/data
cd /var/lib/postgresql/data
rm -rf *
while [ ! -f /archives/base/cur/backup.done ] ; do
  sleep 1
done
tar -xf /archives/base/cur/base.tar.gz
tar -xf /archives/base/cur/pg_wal.tar.gz -C pg_wal
rm -f *.old
rm -f recovery.done

cp /postgresql.conf .
cat /recovery.conf.tmpl | \
  sed s/"PGSQL_FRONTEND_NAME"/"$PGSQL_FRONTEND_NAME"/ | \
  sed s/"PGSQL_RECOVERY_USER"/"$PGSQL_RECOVERY_USER"/ | \
  sed s/"PGSQL_RECOVERY_PASS"/"$PGSQL_RECOVERY_PASS"/ \
  > recovery.conf

chown postgres:postgres . -R
chmod 700 .
