#!/bin/sh

set -e

cd $PGDATA
rm -rf *
chmod 700 .
while [ ! -f /archives/base/cur/backup.done ] ; do
  sleep 1
done
tar -xf /archives/base/cur/base.tar.gz
tar -xf /archives/base/cur/pg_wal.tar.gz -C pg_wal
rm -f *.old
rm -f recovery.done

cat /postgresql.conf.tmpl | \
  sed s/"PGSQL_FRONTEND_NAME"/"$PGSQL_FRONTEND_NAME"/ | \
  sed s/"PGSQL_RECOVERY_USER"/"$PGSQL_RECOVERY_USER"/ | \
  sed s/"PGSQL_RECOVERY_PASS"/"$PGSQL_RECOVERY_PASS"/ \
  > postgresql.conf

touch standby.signal
