#!/bin/sh

let i=0
while (true) ; do
  state=$(psql postgres -c 'SELECT status FROM pg_stat_wal_receiver' -t)
  echo "$state" | grep -q "streaming" && exit 0

  sleep 10s
  let i=i+1

  # 900 seconds (15 minutes) have passed without moving to streaming. Fail.
  [ $i -eq 90 ] && exit 1

  if [ -f /archives/force_master ] ; then
    sudo /bin/rm /archives/force_master
    exit 0
  fi
done
